---
version: "3.8"

services:
  homepage:
    container_name: homepage
    image: ghcr.io/benphelps/homepage:latest
    restart: unless-stopped
    # ports:
    #   - 3000:3000
    volumes:
      - ./config:/app/config
    environment:
      - TZ=Europe/Zurich        

networks:
  default:
    name: local
    external: true
  backend:
    name: backend
    external: true
  remote:
    name: remote
    external: true