---
version: "3.8"

services: 
  dockerproxy:
    container_name: proxy-docker
    image: ghcr.io/tecnativa/docker-socket-proxy:latest
    restart: unless-stopped
    environment:
      - LOG_LEVEL=warning # Log-Levels: debug, info, notice, warning, err, crit, alert, emerg
      - CONTAINERS=1 # Allow access to viewing containers
    networks:
      - backend
    ports:
      - 2375:2375
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

networks:
  default:
    name: local
    external: true
  backend:
    name: backend
    external: true
  remote:
    name: remote
    external: true      