---
# For configuration options and examples, please see:
# https://github.com/benphelps/homepage/wiki/Services

- Networking Utilities:
    - Router_01:
        icon: router.png
        href: http://192.168.10.1
        description: yallo
    - Router_02:
        icon: router.png
        href: http://router.local.springlyo.com
        description: GL-iNet
    - AdGuard:
        icon: https://avatars.githubusercontent.com/u/8361145?s=200&v=4
        # href: http://router.local.springlyo.com:3000
    - Nginx-Proxy:
        icon: https://avatars.githubusercontent.com/u/88089605?s=200&v=4
        href: http://nginx.local.springlyo.com
        server: docker
        container: proxy-nginx
    - Portainer:
        icon: portainer.png
        href: http://portainer.local.springlyo.com
        server: docker
        container: portainer

- Smart Home:
    - Mosquitto:
        icon: mqtt.png
        server: docker
        container: mosquitto
    - Zigbee2mqtt:
        icon: zigbee2mqtt.png
        href: http://z2mqtt.local.springlyo.com
        server: docker
        container: zigbee2mqtt
    - Homeassistant:
        icon: home-assistant.png
        href: http://ha.local.springlyo.com
        server: docker
        container: homeassistant

- Services:
    - Watchtower:
        icon: watchtower.png
        server: docker
        container: watchtower
    - Vaultwarden:
        icon: bitwarden.png
        href: http://vaultwarden.local.springlyo.com
        server: docker
        container: vaultwarden
    - Duplicati:
        icon: duplicati.png
        href: http://duplicati.local.springlyo.com
        server: docker
        container: duplicati
    - Cloudflare Tunnel:
        icon: cloudflare.png
        href: https://one.dash.cloudflare.com
        server: docker
        container: vpn-cloudflare
    - Twingate VPN:
        icon: https://avatars.githubusercontent.com/u/97470429?s=200&v=4
        href: https://springlyo.twingate.com
        server: docker
        container: vpn-twingate
    - Oracle Cloud:
        icon: oracle.png
        href: https://cloud.oracle.com
