---
# For configuration options and examples, please see:
# https://github.com/benphelps/homepage/wiki/Settings

title: Homelab Dashboard
theme: dark # or light
color: slate

headerStyle: boxed

providers:
  openweathermap: b430838a23015a88bb1ebd8b80014bf2
