---
version: "3.8"

services:
  cloudflared:
    container_name: vpn-cloudflare
    image: erisamoe/cloudflared:latest
    restart: always
    networks:
      - remote
    command: tunnel run
    environment:
      - TZ=Europe/Zurich
      - TUNNEL_TOKEN=${TUNNEL_TOKEN}

networks:
  default:
    name: local
    external: true
  backend:
    name: backend
    external: true
  remote:
    name: remote
    external: true