---
version: '3.8'

volumes:
  nginx:
    name: "nginx_data"
  le:
    name: "letsencrypt"

services:
  nginx:
    container_name: proxy-nginx
    image: jc21/nginx-proxy-manager:latest
    restart: always
    networks:
      - backend
      - default
    ports:
      - 80:80
      - 443:443
      - 81:81 # Admin Web Port
    volumes:
      - nginx:/data
      - le:/etc/letsencrypt
    environment:
      DISABLE_IPV6: true
      X_FRAME_OPTIONS: "sameorigin"
    labels:
      - docker-volume-backup.stop-during-backup=nginx

networks:
  default:
    name: local
    external: true
  backend:
    name: backend
    external: true
  remote:
    name: remote
    external: true