---
version: "3.8"

volumes:
  duplicati:
    name: "duplicati_data"

services:
  duplicati:
    container_name: duplicati
    image: duplicati/duplicati:latest
    restart: unless-stopped
    networks:
      - backend
    # ports:
    #   - 8200:8200
    volumes:
      - duplicati:/data
      - /home/dietpi:/source:ro
    environment:
      - TZ=Europe/Zurich
    labels:
      - docker-volume-backup.stop-during-backup=duplicati

networks:
  default:
    name: local
    external: true
  backend:
    name: backend
    external: true
  remote:
    name: remote
    external: true