---
version: "3.8"

volumes:
  data:
    name: "emqx_data"
  log:
    name: "emqx_log"

services:
  emqx:
    container_name: emqx
    image: emqx:latest
    restart: unless-stopped
    network_mode: bridge
    ports:
      - 18083:18083
      - 1883:1883 #tcp

    environment:
      EMQX_NAME: foo_emqx
      EMQX_HOST: 127.0.0.1
    volumes:
      - data:/opt/emqx/data
      - log:/opt/emqx/log